# Generated by Django 4.2.27 on 2025-12-22 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("credits", models.PositiveIntegerField()),
                (
                    "slot",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C1", "C1"), ("C2", "C2")],
                        max_length=5,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        limit_choices_to={"role": "Faculty"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
