# Generated by Django 4.2.27 on 2025-12-22 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.FloatField(blank=True, null=True)),
                ("attendance", models.PositiveIntegerField(default=0)),
                ("grade", models.CharField(blank=True, max_length=2, null=True)),
                ("revaluation_requested", models.BooleanField(default=False)),
                ("revaluation_approved", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "Student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="core.subject",
                    ),
                ),
            ],
            options={"unique_together": {("student", "subject")},},
        ),
    ]
